language: node_js

node_js:
- 13

addons:
  apt:
    packages:
    # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
    # in order to work with Cypress
    - libgconf-2-4

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"

install:
- npm ci

before_script:
# Start the server, where `&` tells travis to run it as a
# non-blocking background process
- npm start -- --silent &

script:
# - npm test
- npm run cypress:run

deploy:
  provider: heroku
  app: mzjmes
  api_key:
    secure: Wz6my6uYqKGxR2YxafSY9uqSM3kRmIv/LNuEU72SBTed2POnc/69XBCT8vb11+4Xj5duP6QENmpy4tEfqNsh/oyawv60dr0h+ZzktuQ0dRp1kf+bXViFiiVkmyIDHJQk+aztvG8KZhJG1leNPtvGwrEvkoZR/M/UHR6VuNkgLqQTlql+ugqffxOsfigkI68mufk2eOZEBy0zXeOsdGeHTJr1aOWrET5PiuN0RmlK8pPKMi7ulirXHvtunnyQNdbvymGWueiPbfv3tifw8XXheB9YLjboc5phXRKMoR8AJSW2lPTJmdDRIem8vME78ACHfobsJ/CZJhsDsMWtUOkzcfzJ6mevMqg3duCBmyNxw/BzxB+rdUd+OlUXC31Uk5zkZcbJmm8W5uPLLkrfqPx8oPb5doZO61BksyGY18o+nv76b1EOF2yT1z2gZoeyLt7wrpTeg8PgvAtYpzim2B3OBsc7YwrQhDs/w8+CxlU3vRkElYhUEMobynQW9hRMFC6p2PvIZU9d3huJe6uFKY6XOlsE75vJEi3ghMP0mfAfEYueRBmGtYGFSLjPPrbVAGG58P1leLXa2MnYvYz1W7GlTLVTfBZvluphIKELglDdbYZOZIGRUfhNHTD7ccTZ72LjU3s3rp1GV+4DjKLs+jibvtMfDIgRJPcOt+78moVtx2c=
