language: node_js

node_js:
- 13

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"

install:
- npm ci

script:
- npm test

deploy:
  provider: heroku
  app: ftjmes
  api_key:
    secure: Wz6my6uYqKGxR2YxafSY9uqSM3kRmIv/LNuEU72SBTed2POnc/69XBCT8vb11+4Xj5duP6QENmpy4tEfqNsh/oyawv60dr0h+ZzktuQ0dRp1kf+bXViFiiVkmyIDHJQk+aztvG8KZhJG1leNPtvGwrEvkoZR/M/UHR6VuNkgLqQTlql+ugqffxOsfigkI68mufk2eOZEBy0zXeOsdGeHTJr1aOWrET5PiuN0RmlK8pPKMi7ulirXHvtunnyQNdbvymGWueiPbfv3tifw8XXheB9YLjboc5phXRKMoR8AJSW2lPTJmdDRIem8vME78ACHfobsJ/CZJhsDsMWtUOkzcfzJ6mevMqg3duCBmyNxw/BzxB+rdUd+OlUXC31Uk5zkZcbJmm8W5uPLLkrfqPx8oPb5doZO61BksyGY18o+nv76b1EOF2yT1z2gZoeyLt7wrpTeg8PgvAtYpzim2B3OBsc7YwrQhDs/w8+CxlU3vRkElYhUEMobynQW9hRMFC6p2PvIZU9d3huJe6uFKY6XOlsE75vJEi3ghMP0mfAfEYueRBmGtYGFSLjPPrbVAGG58P1leLXa2MnYvYz1W7GlTLVTfBZvluphIKELglDdbYZOZIGRUfhNHTD7ccTZ72LjU3s3rp1GV+4DjKLs+jibvtMfDIgRJPcOt+78moVtx2c=
